format_code_in_doc_comments = true
match_block_trailing_comma = true
reorder_imports = true
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
normalize_comments = true
overflow_delimited_expr = true
reorder_impl_items = true
use_field_init_shorthand = true
use_try_shorthand = true
